# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -buildvcs=false -o ./tmp/main"
bin = "tmp/main"
full_bin = "tmp/main"
exclude_dir = ["tmp", "vendor"]
include_ext = ["go", "tmpl", "tpl"]

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
