// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/chain_gateway.proto

package chain_gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Reusable record for content entries
type ContentRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`                                           // Unique identifier to bind transaction to page version
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`                                           // Page URL
	ContentHash   string                 `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`        // SHA-256 hash of page content
	ContentLength uint64                 `protobuf:"varint,4,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"` // Size of original content in bytes
	Version       uint32                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`                                  // Schema version number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentRecord) Reset() {
	*x = ContentRecord{}
	mi := &file_proto_chain_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentRecord) ProtoMessage() {}

func (x *ContentRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentRecord.ProtoReflect.Descriptor instead.
func (*ContentRecord) Descriptor() ([]byte, []int) {
	return file_proto_chain_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *ContentRecord) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ContentRecord) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ContentRecord) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *ContentRecord) GetContentLength() uint64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *ContentRecord) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Request to store a content record
type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ContentRecord         `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_proto_chain_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *StoreRequest) GetRecord() *ContentRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

// Response after storing a record
type StoreResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TransactionId  string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`    // On-chain transaction ID
	AccountAddress string                 `protobuf:"bytes,3,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"` // Solana account address where proof is stored
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_proto_chain_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *StoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *StoreResponse) GetAccountAddress() string {
	if x != nil {
		return x.AccountAddress
	}
	return ""
}

var File_proto_chain_gateway_proto protoreflect.FileDescriptor

const file_proto_chain_gateway_proto_rawDesc = "" +
	"\n" +
	"\x19proto/chain_gateway.proto\x12\rchain_gateway\"\x97\x01\n" +
	"\rContentRecord\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12!\n" +
	"\fcontent_hash\x18\x03 \x01(\tR\vcontentHash\x12%\n" +
	"\x0econtent_length\x18\x04 \x01(\x04R\rcontentLength\x12\x18\n" +
	"\aversion\x18\x05 \x01(\rR\aversion\"D\n" +
	"\fStoreRequest\x124\n" +
	"\x06record\x18\x01 \x01(\v2\x1c.chain_gateway.ContentRecordR\x06record\"y\n" +
	"\rStoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12'\n" +
	"\x0faccount_address\x18\x03 \x01(\tR\x0eaccountAddress2R\n" +
	"\fChainGateway\x12B\n" +
	"\x05Store\x12\x1b.chain_gateway.StoreRequest\x1a\x1c.chain_gateway.StoreResponseB-Z+internal/client/chain_gateway;chain_gatewayb\x06proto3"

var (
	file_proto_chain_gateway_proto_rawDescOnce sync.Once
	file_proto_chain_gateway_proto_rawDescData []byte
)

func file_proto_chain_gateway_proto_rawDescGZIP() []byte {
	file_proto_chain_gateway_proto_rawDescOnce.Do(func() {
		file_proto_chain_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chain_gateway_proto_rawDesc), len(file_proto_chain_gateway_proto_rawDesc)))
	})
	return file_proto_chain_gateway_proto_rawDescData
}

var file_proto_chain_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_chain_gateway_proto_goTypes = []any{
	(*ContentRecord)(nil), // 0: chain_gateway.ContentRecord
	(*StoreRequest)(nil),  // 1: chain_gateway.StoreRequest
	(*StoreResponse)(nil), // 2: chain_gateway.StoreResponse
}
var file_proto_chain_gateway_proto_depIdxs = []int32{
	0, // 0: chain_gateway.StoreRequest.record:type_name -> chain_gateway.ContentRecord
	1, // 1: chain_gateway.ChainGateway.Store:input_type -> chain_gateway.StoreRequest
	2, // 2: chain_gateway.ChainGateway.Store:output_type -> chain_gateway.StoreResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_chain_gateway_proto_init() }
func file_proto_chain_gateway_proto_init() {
	if File_proto_chain_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chain_gateway_proto_rawDesc), len(file_proto_chain_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chain_gateway_proto_goTypes,
		DependencyIndexes: file_proto_chain_gateway_proto_depIdxs,
		MessageInfos:      file_proto_chain_gateway_proto_msgTypes,
	}.Build()
	File_proto_chain_gateway_proto = out.File
	file_proto_chain_gateway_proto_goTypes = nil
	file_proto_chain_gateway_proto_depIdxs = nil
}
